language: python
dist: xenial
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

before_install:
  - uname -a
  - python --version
  - virtualenv --version
  - pip --version

install:
  - pip install tox
  - tox --version

stages:
  - check
  - test
  - coverage_report

matrix:
  include:
    - stage: check
      python: '2.7'
      env: TOXENV=check27
    - python: '3.6'
      env: TOXENV=check36

    - stage: test
      python: '2.7'
      env: TOXENV=py27
    - python: 'pypy'
      env: TOXENV=pypy
    - python: '3.4'
      env: TOXENV=py34
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36

    - stage: coverage_report
    - python: '3.6'
      env: TOXENV=coverage


script:
  - tox -v

cache: pip